/**
 * A főoldali „Ez érkezett ma” szekció három teljes meséje.
 * Bekezdésenként egy tömbelem – a felolvasó nézet így tudja tördelni.
 */

export const storyBodies: Record<string, string[]> = {
  "A hold, aki elaludt": [
    "Aznap este hiányzott valami az égről.",
    "Marci vette észre először, mert ő szokott utoljára kinézni az ablakon. Máskor a Hold ott ült a templomtorony fölött, mint egy nagy, sárga gomb. Most csak a sötétkék ég volt ott, meg néhány álmos csillag.",
    "– Anya, elgurult a Hold – mondta Marci.",
    "Anya odalépett az ablakhoz, és sokáig nézte az eget. Aztán elmosolyodott.",
    "– Nem gurult el. Szerintem csak elaludt.",
    "– A Hold is alszik?",
    "– Néha. Nagyanyám mesélte, hogy régen is megesett. Olyankor el kell menni érte.",
    "Marci pizsamában és gumicsizmában indult el, mert ilyenkor ez a szokás. A szomszéd kertkapunál már ott állt Bori a plüsstigrisével, mögötte Zalán, akinek mindig volt valami a zsebében. Most éppen egy fél zsömle.",
    "– Hallottátok? – suttogta Bori.",
    "– A Hold alszik – bólintott Marci. – Fel kell ébreszteni.",
    "– De halkan – tette hozzá Zalán. – Mert aki alszik, azt csak őt szabad felébreszteni. Mást nem.",
    "Ezt mind a hárman nagyon komolyan vették.",
    "Elindultak a domb felé, ahonnan a Hold szokott feljönni. Az utca olyan csendes volt, hogy hallották a saját lépteiket. Bori a tigrist a kabátja alá dugta, nehogy az is felébredjen.",
    "A kerítés mellett Böfi, a szomszéd kutya aludt, orrát a mancsára fektetve. Lábujjhegyen mentek el mellette. Böfi megrezzent, sóhajtott egyet, aztán aludt tovább.",
    "A pékség előtt a kirakatban ott sorakoztak a holnapi kiflik. Zalán megállt volna, de Marci megrázta a fejét.",
    "A tó partján hat kacsa aludt egymás mellett, mint hat kis párna. A gyerekek megvárták, amíg elül a szél, és csak utána léptek tovább.",
    "Csak a bagoly volt ébren. Ült az öreg fűzfán, és pislogott.",
    "– Hova mentek? – kérdezte.",
    "– Felébreszteni a Holdat – felelte Marci.",
    "– Régóta várom már – mondta a bagoly. – Nélküle nem látok rendesen. Menjetek csak, a domb mögött van.",
    "És tényleg ott volt.",
    "A domb túloldalán, a fűben feküdt a Hold. Nagy volt és sárga, és összegömbölyödött, mint egy macska. Egyenletesen szuszogott, és minden lélegzetnél kicsit halványabb, aztán kicsit fényesebb lett.",
    "– Ébreszd fel te – súgta Bori.",
    "– Ébreszd fel te – súgta vissza Marci.",
    "Zalán nagy levegőt vett, mint aki kiabálni készül. A másik kettő rögtön a szája elé kapta a kezét.",
    "– Halkan – emlékeztette Bori.",
    "Először megpróbálták megkocogtatni. A Hold csak fordult egyet.",
    "Aztán megpróbálták csiklandozni. A Hold elmosolyodott álmában, de nem ébredt fel.",
    "Végül Bori előhúzta a tigrist a kabátja alól, leült a fűbe, és halkan dúdolni kezdte azt a dalt, amit otthon szoktak, amikor ő nem tud elaludni. Marci is beszállt. Zalán nem tudta a szöveget, ezért csak nagyon csendesen dünnyögött hozzá.",
    "A Hold kinyitotta a szemét.",
    "Ásított egy nagyot, ami olyan volt, mint egy nagy sárga karika az égen. Aztán nyújtózott, és lassan, kicsit nehézkesen felkelt a fűből. Ahogy emelkedett, az egész domb megtelt fénnyel: a fűszálak, a tó vize, Bori tigrisének a füle, minden ezüstös lett.",
    "– Köszönöm – mondta a Hold, olyan halkan, hogy inkább csak érezni lehetett, mint hallani. – Néha én is elfáradok.",
    "– Semmi baj – felelte Marci. – Mi is.",
    "Hazafelé már nem beszéltek. A bagoly biccentett nekik a fűzfáról. A kacsák aludtak tovább. Böfi meg sem mozdult.",
    "Bori a kapuban intett, Zalán elmajszolta a fél zsömlét, Marci pedig felment a lépcsőn, és lerúgta a gumicsizmát.",
    "Anya betakarta.",
    "– Megtaláltátok? – kérdezte.",
    "Marci bólintani akart, de addigra már az ablakon besütött a holdfény, és a szemhéja is nehéz lett.",
    "Odakint pedig a Hold ott ült a templomtorony fölött, ébren, és vigyázott az egész városra.",
  ],

  "Bátor Samu és a viharos tó": [
    "Samu, a sünfiú két dolgot szeretett a világon a legjobban: a nagypapát és a nagypapa csónakját.",
    "A csónak zöldre volt festve, az orrán fehér betűkkel az állt, hogy Bogáncs, és a nádas szélén ringott egy kikötőcölöphöz kötve. Samu minden nyáron ott ült a partján, és nézte, ahogy a víz nekiütődik az oldalának.",
    "– Mikor mehetek ki vele egyedül? – kérdezte legalább hetente egyszer.",
    "– Ha már tudod, mikor kell visszafordulni – felelte a nagypapa.",
    "Samu ezt sosem értette. Szerinte a bátorsághoz az kell, hogy az ember elinduljon. A visszafordulás pont az ellenkezője.",
    "Egy augusztusi reggelen a nagypapa a piacra ment, és Samu egyedül maradt a háznál. A tó sima volt, mint egy tükör. Egyetlen felhő sem látszott.",
    "„Ma van az a nap” – gondolta Samu.",
    "Kioldotta a kötelet, beült a csónakba, és nekiveselkedett az evezőnek. Nehezebb volt, mint gondolta. Az első tíz csapás után a part még mindig ott volt mögötte, de a huszadiknál már távolodott, és Samu érezte, hogy a hasában bizsereg valami. Nem félelem. Inkább öröm.",
    "Elevezett a nádas mellett, ahol a szárcsák úszkáltak. Elevezett a kidőlt fűzfa mellett, amiről a nagypapa azt mesélte, hogy egy villám döntötte ki, még az ő gyerekkorában. Aztán elevezett a szigetig, ami tulajdonképpen csak egy nagy zsombék volt három bokorral, de Samu mindig szigetnek hívta.",
    "Ott megállt, felhúzta az evezőt, és hanyatt feküdt a csónak alján.",
    "Fölötte az ég.",
    "Az ég viszont már nem volt egészen olyan, mint reggel.",
    "Nyugat felől szürke csík húzódott a víz fölé, és az a csík egyre szélesedett. A nád zizegni kezdett. A szárcsák eltűntek valahova. A víz elvesztette a tükörsimaságát, és apró, ideges fodrok futottak végig rajta.",
    "Samu felült.",
    "A túlsó part még mindig messze volt. Ha odaevez, akkor egy órán belül megkerülheti az egész tavat, és elmondhatja a nagypapának, hogy megcsinálta. Ha viszont visszafordul, akkor csak annyi történt, hogy kievezett a szigetig, mint egy kisgyerek.",
    "Belemarkolt az evezőbe, és a túlsó part felé fordította a csónakot.",
    "Az első széllökés oldalról érkezett.",
    "A csónak megbillent, Samu tüskéi felmeredtek, és a víz átcsapott a peremen. Nem sok, csak egy pohárnyi, de hideg volt, és Samu hirtelen nagyon egyedül érezte magát a tó közepén.",
    "A második széllökés már nagyobb volt.",
    "Samu evezett tovább, mert eldöntötte, hogy evez. Aztán észrevette, hogy hiába húzza az evezőt, a túlsó part nem közeledik. A szél pontosan szemből fújt.",
    "És akkor eszébe jutott a nagypapa hangja: „Ha már tudod, mikor kell visszafordulni.”",
    "Samu megállt egy pillanatra.",
    "Nagyon nem akart visszafordulni. Már majdnem sírt is a mérgétől. De ahogy ott ült a hullámzó csónakban, rájött valamire: a nagypapa nem azt mondta, hogy „ha már nem félsz”. Azt mondta, hogy „ha már tudod”.",
    "Beleeresztette az evezőt a vízbe, és lassan, óvatosan megfordította a csónakot.",
    "Onnantól a szél a háta mögül fújt.",
    "Nem lett könnyebb, mert a hullámok oldalról nekicsapódtak a csónaknak, és Samunak minden erejével egyensúlyoznia kellett. De haladt. A kidőlt fűzfa elmaradt mellette. A nádas is. A part egyre közelebb ért, aztán már a kikötőcölöpöt is látta.",
    "Amikor a csónak orra nekikoccant a partnak, elkezdett esni az eső.",
    "Samu kikötötte a Bogáncsot, ahogy a nagypapa tanította, dupla csomóval, és leült a stégre a szakadó esőben. Csuromvizes lett. Nem érdekelte.",
    "A nagypapa fél óra múlva ért haza, egy szatyor paradicsommal és egy fél kiló mogyoróval.",
    "Megállt a stég végén, és végignézett a csónakon, a dupla csomón, meg a csuromvizes Samun.",
    "– Kimentél – mondta.",
    "– Ki – felelte Samu. – A szigetig. Aztán tovább akartam menni, és jött a szél, és… visszafordultam.",
    "A nagypapa leült mellé. Egy ideig csak nézték az esőt.",
    "– Tudod, mi a legnehezebb a csónakban? – kérdezte végül.",
    "– Az evezés?",
    "– Nem. Az, hogy megfordulj, amikor már majdnem odaértél.",
    "Samu erre nem tudott mit mondani. Kicsit még mindig bosszankodott, de közben valahogy melege lett belülről.",
    "– Jövő héten – mondta a nagypapa, és feltört egy mogyorót – kimehetünk ketten a túlsó partig. Megmutatom, honnan lehet előre látni a szelet.",
    "– És ha megint jön a vihar?",
    "– Akkor megint visszafordulunk – vonta meg a vállát a nagypapa. – Attól még kimentünk.",
    "Aznap este Samu a tetőn kopogó esőt hallgatta, és arra gondolt, hogy a bátorság mégiscsak kétféle. Van, amelyik elindul, és van, amelyik hazahoz.",
    "Aztán elaludt, mielőtt eldönthette volna, melyik a nehezebb.",
  ],

  "Miért mérges a kis sárkány?": [
    "Zente sárkány volt, méghozzá elég kicsi. Akkora, mint egy nagyobbacska kutya, csak zöldebb, és a hátán tüskesor futott végig.",
    "Egy dologban viszont egyáltalán nem volt kicsi: a mérgében.",
    "Ha valami nem sikerült, Zente orrából kicsapott a füst. Nem nagy tűz, nem lángok, csak sűrű, szürke füst, ami megült a barlangban, és mindenki köhögött tőle.",
    "Reggel füstölt, mert a bakancsa szíja összegabalyodott.",
    "Délelőtt füstölt, mert a torony, amit épített, összedőlt.",
    "Ebédnél füstölt, mert a leves túl forró volt.",
    "Délután pedig azért füstölt, mert a barátai már nem akartak vele játszani, és ettől lett a legmérgesebb.",
    "– Nem is vagyok mérges! – kiabálta, és közben akkora füstfelhő szállt fel, hogy a napot is eltakarta.",
    "Anyukája leült mellé.",
    "– Nem baj, ha mérges vagy – mondta. – Csak nem tudod, mit kezdj vele.",
    "– Nincs mit kezdeni vele – morogta Zente. – Csak úgy jön.",
    "– Menj el Teodorhoz.",
    "Teodor a tó partján lakott, egy lapos kövön. Nagyon öreg teknős volt, olyan öreg, hogy a páncélján zuzmó nőtt. Zente dobogva ért oda, és már messziről füstölt.",
    "– Azt mondták, tudsz valamit a méregről – vetette oda.",
    "Teodor lassan kinyitotta a szemét.",
    "– Tudok. Ülj le.",
    "– Nem akarok leülni.",
    "– Akkor állj. De ott, ahol vagy.",
    "Zente állt, és fújta a füstöt. Teodor nem szólt semmit. Csak nézte a tavat. Egy perc telt el, aztán még egy.",
    "– Ez a válaszod? – csattant fel Zente. – Hogy álljak?",
    "– Az a válaszom – mondta Teodor –, hogy a méreg olyan, mint egy hullám. Jön, felemel, aztán leszalad. Aki hullám közben kezd kapálózni, azt bevágja a partra. Aki megvárja, azt leteszi.",
    "– És addig mit csináljak?",
    "– Három lassú lélegzetet.",
    "Zente majdnem újra kifújta a füstöt, annyira butaságnak tartotta. De Teodor olyan nyugodtan nézett rá, hogy inkább kipróbálta.",
    "Az első lélegzet még akadozott. Rövid volt, éles, és a végén megint elkapta a düh.",
    "A második már hosszabb lett. Zente érezte, hogy a mellkasa kitágul, aztán lassan visszaenged.",
    "A harmadiknál valami furcsa történt. A füst egyszerűen elmaradt. Zente kifújta a levegőt, és nem jött vele semmi. Csak levegő.",
    "– Ez… – kezdte, aztán elhallgatott.",
    "– Nem múlt el a mérged – mondta Teodor. – Csak most már te tartod, nem ő téged.",
    "Zente leült a kőre. Odabent még mindig ott volt a düh, de olyan volt, mint egy meleg kavics: érezte, tudta, hol van, és nem égette.",
    "– És mindig működik?",
    "– Nem – felelte az öreg teknős őszintén. – Néha négy lélegzet kell. Néha tíz. Néha az kell, hogy elmondd valakinek, mi történt.",
    "Aznap este Zente még kétszer kezdett füstölni. Egyszer, amikor kiderült, hogy nincs több sült alma. Egyszer meg, amikor a bakancsa szíja megint összegabalyodott.",
    "Mind a kétszer megállt, és számolt: egy lassú, két lassú, három lassú.",
    "A barlang tiszta maradt.",
    "Lefekvéskor anyukája beült mellé a szalmára.",
    "– Ma nem volt füst – mondta.",
    "– De mérges voltam – vallotta be Zente. – Kétszer is. Elég nagyon.",
    "– Tudom. Láttam.",
    "– És akkor is jó?",
    "– Akkor a legjobb – felelte az anyukája. – Mérgesnek lenni szabad. Csak azt kell megtanulni, hogy közben ne égessük meg azt, aki mellettünk áll.",
    "Zente ezen gondolkodott egy darabig. Aztán ásított, és a tüskéi ellazultak a hátán.",
    "Odakint a hold sütött, a barlangban nem volt füst, és Zente elaludt, mielőtt a harmadik lassú lélegzet a végére ért volna.",
  ],
};
